#include "generalheaders/tables.h"
Oper_t Oper_table [_OPERDATASIZE_] =    {
                                        {"RAISE",      "_MATH_ADD_",           OP_ADD,             strlen("RAISE"),     INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmAdd,},
                                        {"FOLD",       "_MATH_SUB_",           OP_SUB,             strlen("FOLD"),      INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSub,},
                                        {"ALLIN",      "_MATH_MUL_",           OP_MUL,             strlen("ALLIN"),     INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmMul,},
                                        {"CHECK",      "_MATH_DIV_",           OP_DIV,             strlen("CHECK"),     INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmDiv,},
                                        {"SQRT",       "_MATH_SQRT_",          OP_SQRT,            strlen("SQRT"),      INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSqrt,},
                                        {"POW",        "_MATH_POW_",           OP_POW,             strlen("POW"),       INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"SNAP",       "_MATH_EQUAL_",         OP_EQ,              strlen("SNAP"),      INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"MUCK",       "_MATH_NOT_EQUAL_",     OP_NEQ,             strlen("MUCK"),      INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"BUMP",       "_MATH_ABOVE_EQ_",      OP_ABOVE_EQ,        strlen("BUMP"),      INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"TANK",       "_MATH_BELOW_EQ_",      OP_BELOW_EQ,        strlen("TANK"),      INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"TILT",       "_MATH_BELOW_",         OP_BELOW,           strlen("TILT"),      INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"SHOVE",      "_MATH_ABOVE_",         OP_ABOVE,           strlen("SHOVE"),     INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"NIT",        "_MATH_NOT_",           OP_NOT,             strlen("NIT"),       OTHER_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"FLOP",       "_MATH_AND_",           OP_AND,             strlen("FLOP"),      OTHER_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"RIVER",      "_MATH_OR_",            OP_OR,              strlen("RIVER"),     OTHER_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"(",          "(",                    OPEN_R_BR,          strlen("("),         OTHER_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {")",          ")",                    CLOSE_R_BR,         strlen(")"),         OTHER_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"BUYIN",      "[",                    OPEN_SQ_BR,         strlen("BUYIN"),     OTHER_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"CASHOUT",    "]",                    CLOSE_SQ_BR,        strlen("CASHOUT"),   OTHER_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"ANTE",       "{",                    OPEN_FIG_BR,        strlen("ANTE"),      OTHER_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"POT",        "}",                    CLOSE_FIG_BR,       strlen("POT"),       OTHER_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"BLUFF?",     "_IF_",                 OP_IF,              strlen("BLUFF?"),    PREFIX_ORD,   GetAsmSkip,       GetAsmInfixIf,     GetAsmPostIf,},
                                        {"CHECKBACK",  "_ELSE_",               OP_ELSE,            strlen("CHECKBACK"), PREFIX_ORD,   GetAsmSkip,       GetAsmInfixElse,   GetAsmPostElse,},
                                        {"WHILESTACK", "_WHILE_",              OP_WHILE,           strlen("WHILESTACK"),PREFIX_ORD,   GetAsmSkip,       GetAsmInfixWhile,  GetAsmPostWhile,},
                                        {"FOR",        "_FOR_",                OP_FOR,             strlen("FOR"),       PREFIX_ORD,   GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"BOUNTY",     "_RETURN_",             OP_RET,             strlen("BOUNTY"),    PREFIX_ORD,   GetAsmSkip,       GetAsmSkip,        GetAsmRet,},
                                        {"PASS",       "_BREAK_",              OP_BREAK,           strlen("PASS"),      PREFIX_ORD,   GetAsmSkip,       GetAsmSkip,        GetAsmRet,},//brrr asm
                                        {"BET",        "_ASSIGNMENT_",         OP_ASSIGN,          strlen("BET"),       INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmAssign,},
                                        {"$",          "$",                    OP_END,             strlen("$"),         OTHER_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"BUYSTRAT",   "_FUNC_DECLARE_",       OP_F_DCLR,          strlen("BUYSTRAT"),  PREFIX_ORD,   GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"FREEBET",    "_VAR_DECLARE_",        OP_V_DCLR,          strlen("FREEBET"),   PREFIX_ORD,   GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {",",          "_COMMA_",              OP_COMMA,           strlen(","),         INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmSkip,},
                                        {"TURN",       "_END_STATEMENT_",      OP_STR_END,         strlen("TURN"),      INFIX_ORD,    GetAsmSkip,       GetAsmSkip,        GetAsmStrEnd,},
                                        {"CALL",       "_PRINT_",              OP_PRINT,           strlen("CALL"),      PREFIX_ORD,   GetAsmSkip,       GetAsmSkip,        GetAsmPrint,},
                                        {"READ",       "_SCAN_",               OP_SCAN,            strlen("READ"),      PREFIX_ORD,   GetAsmSkip,       GetAsmSkip,        GetAsmScanf,},
                                        {"MEMGET",     "memget",               OP_MEMGET,          strlen("MEMGET"),    PREFIX_ORD,   GetAsmMemget,     GetAsmMemget,      GetAsmMemget,},
                                        {"MEMSET",     "memset",               OP_MEMSET,          strlen("MEMSET"),    PREFIX_ORD,   GetAsmMemset,     GetAsmMemset,      GetAsmMemset,},
                                        };
VarStack_t Var_table = {};
FuncStack_t Func_table = {};
FILE *Logfile = NULL;
